name: Reuseable-workflow

on:
  workflow_call:
    secrets:
      apisec_username:
        required: true
      apisec_password:
        required: true
    inputs:
#       apisec_username:
#         required: true
#         type: string 
#       apisec_password:
#         required: true 
#         type: string 
      apisec-project:
        required: true
        type: string   
      apisec-profile:
        required: false
        type: string  
      apisec-region:
        required: false
        type: string
      sarif-result-file:
        required: false
        type: string   
      apisec-email-report:
        required: false
        type: string           
      apisec-fail-on-high-vulns:
        required: false
        type: string   
      apisec-oas:
        required: false
        type: string 
      apisec-openapi-spec-url:
        required: false
        type: string 
      apisec-refresh-playbooks:  
        required: false
        type: string 
      apisec-hostname:  
        required: false
        type: string 
      apisec-scan-all-projects:  
        required: false
        type: string         
       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: APIsec Scan
  # You may pin to the exact commit or the version.
  # uses: apisec-inc/apisec-run-scan@159dff575c9da6ecbb647ab5f630701331197de8
        #uses: apisec-inc/apisec-run-scan@v1.0.6
        uses: SyedsImran/NewDrone@v1.0.3
        with:
          apisec-username: ${{ secrets.apisec_username }}
          apisec-password: ${{ secrets.apisec_password }}
          apisec-project: ${{ inputs.apisec-project }}
          apisec-profile: ${{ inputs.apisec-profile }}
          apisec-region: ${{ inputs.apisec-region }}
          sarif-result-file: ${{ inputs.sarif-result-file }}
          apisec-email-report: ${{ inputs.apisec-email-report }}
          apisec-fail-on-high-vulns: ${{ inputs.apisec-fail-on-high-vulns }}
          apisec-oas: ${{ inputs.apisec-oas }}
          apisec-openapi-spec-url: ${{ inputs.apisec-openapi-spec-url }}
          apisec-refresh-playbooks: ${{ inputs.apisec-refresh-playbooks }}
          apisec-scan-all-projects: ${{ inputs.apisec-scan-all-projects }}
          apisec-hostname: ${{ inputs.apisec-scan-all-projects }}

      - name: upload sarif file to repository
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./${{ inputs.sarif-result-file }}
